// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'BUATSENDIRI',
    appId: '1:310285663487:web:a6ce5a1890fc74166be0ca',
    messagingSenderId: '310285663487',
    projectId: 'myanime-b409e',
    authDomain: 'myanime-b409e.firebaseapp.com',
    storageBucket: 'myanime-b409e.appspot.com',
    measurementId: 'G-XKPVWGEQBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'BUATSENDIRI',
    appId: '1:310285663487:android:96edf53260ecea2c6be0ca',
    messagingSenderId: '310285663487',
    projectId: 'myanime-b409e',
    storageBucket: 'myanime-b409e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'BUATSENDIRI',
    appId: '1:310285663487:ios:e61ef178b53b0a006be0ca',
    messagingSenderId: '310285663487',
    projectId: 'myanime-b409e',
    storageBucket: 'myanime-b409e.appspot.com',
    iosClientId: '310285663487-7etb4c653h0k9724747emmkp0c1il8sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myanime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'BUATSENDIRI',
    appId: '1:310285663487:ios:e61ef178b53b0a006be0ca',
    messagingSenderId: '310285663487',
    projectId: 'myanime-b409e',
    storageBucket: 'myanime-b409e.appspot.com',
    iosClientId: '310285663487-7etb4c653h0k9724747emmkp0c1il8sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myanime',
  );
}
